// client/src/components/ArtForm.jsx
import { useState } from "react";
import CatalogueItem from "./CatalogueItem";

const ArtForm = () => {
  const baseURL = import.meta.env.VITE_BASE_URL;
  const apiBaseURL = import.meta.env.VITE_API_BASE_URL;

  const sections = [
    "Ceramics",
    "Electronic Arts",
    "Jewellery",
    "Painting",
    "Photography",
    "Print",
    "Sculpture",
    "Textiles",
  ];

  const [message, setMessage] = useState(null);
  const [formData, setFormData] = useState({
    firstName: "",
    lastName: "",
    title: "",
    section: sections[0],
    medium: "",
    siteMap: 1,
  });
  const [items, setItems] = useState([]);
  const [submitted, setSubmitted] = useState(false);
  const [errors, setErrors] = useState({});

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData((prevFormData) => ({
      ...prevFormData,
      [name]: value,
    }));
  };

  const addItem = () => {
    const newItem = {
      title: "",
      medium: "",
      dimensions: "",
      hasEdition: false,
      editions: "",
      nfs: false,
      value: "",
    };
    setItems([...items, newItem]);
  };

  const handleItemChange = (id, updatedItem) => {
    setItems((prevItems) =>
      prevItems.map((item, index) => (index === id ? updatedItem : item))
    );
  };

  const deleteItem = (id) => {
    setItems((prevItems) => prevItems.filter((_, index) => index !== id));
  };

  const onSubmit = async (e) => {
    e.preventDefault();

    setSubmitted(true);

    if (items.length === 0) {
      setMessage("Please add at least one item to the catalogue.");
      return;
    }

    if (window.confirm("Press OK if your information is correct?")) {
      setMessage("Submitting...");

      const formattedItems = items.map((item) => ({
        ...item,
        editions: item.editions ? parseInt(item.editions, 10) : null,
        value: item.value ? parseFloat(item.value) : null,
      }));

      try {
        const res = await fetch(`${apiBaseURL}/catalogue-items`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            firstName: formData.firstName,
            lastName: formData.lastName,
            siteMap: parseInt(formData.siteMap, 10),
            section: formData.section,
            items: formattedItems,
          }),
        });

        const data = await res.json();

        if (!res.ok) {
          setMessage("Submission unsuccessful.");
          setErrors(data.errors || {});
        } else {
          setMessage("Submission successful.");
          setFormData({
            firstName: "",
            lastName: "",
            title: "",
            section: sections[0],
            medium: "",
            siteMap: 1,
          });
          setItems([]);
          setErrors({});
          setSubmitted(false);
        }
      } catch (error) {
        setMessage("Submission unsuccessful.");
      }
    }
  };

  return (
    <article className="max-w-3xl mx-auto p-6 bg-white shadow-md rounded-md">
      <header>
        <h1 className="text-2xl font-bold text-gray-700 mb-4">
          Dunedin School of Art - SITE 2024
        </h1>
        <p className="text-gray-700 mb-4">
          You can find your entry information here -{" "}
          <a
            href="/entries"
            target="_blank"
            rel="noreferrer"
            className="text-blue-500 underline"
          >
            {baseURL}/entries
          </a>
        </p>
      </header>

      <section aria-labelledby="form-instructions">
        <hr className="border-gray-300 my-4" />
        <p id="form-instructions" className="text-gray-700 mb-4">
          Fill out the following form to add your art to the catalogue.
        </p>
        {message && <p className="text-red-600 mb-4 font-medium">{message}</p>}
      </section>

      <form autoComplete="off" onSubmit={onSubmit}>
        <fieldset className="mb-4">
          <legend className="text-lg font-semibold text-gray-700">
            Artist Information
          </legend>

          <label className="block text-gray-700 mt-4">First Name</label>
          <input
            type="text"
            name="firstName"
            placeholder="First Name"
            value={formData.firstName}
            onChange={handleInputChange}
            className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
          />
          {submitted && errors.firstName && (
            <p className="text-red-500">First name is required.</p>
          )}

          <label className="block text-gray-700 mt-4">Last Name</label>
          <input
            type="text"
            name="lastName"
            placeholder="Last Name"
            value={formData.lastName}
            onChange={handleInputChange}
            className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
          />
          {submitted && errors.lastName && (
            <p className="text-red-500">Last name is required.</p>
          )}

          <label className="block text-gray-700 mt-4">SITE Map Number</label>
          <input
            type="number"
            name="siteMap"
            value={formData.siteMap}
            onChange={handleInputChange}
            className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
          />
          {submitted && errors.siteMap && (
            <p className="text-red-500">
              Site map must be a number greater than 0.
            </p>
          )}

          <label className="block text-gray-700 mt-4">Section</label>
          <select
            name="section"
            value={formData.section}
            onChange={handleInputChange}
            className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
          >
            {sections.map((section, index) => (
              <option key={index} value={section}>
                {section}
              </option>
            ))}
          </select>
        </fieldset>

        <fieldset className="mb-4">
          <legend className="text-lg font-semibold text-gray-700">
            Catalogue Items
          </legend>
          <div className="mt-4">
            {items.map((item, index) => (
              <CatalogueItem
                key={index}
                id={index}
                item={item}
                onChange={handleItemChange}
                onDelete={deleteItem}
                submitted={submitted}
                errors={errors}
              />
            ))}
          </div>

          <button
            type="button"
            onClick={addItem}
            className="w-full py-2 px-4 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none"
          >
            Add Another Catalogue Item
          </button>
        </fieldset>

        <section>
          <p className="text-gray-700">
            Please note that Otago Polytechnic takes a 25% commission.
          </p>
        </section>

        <button
          type="submit"
          className="w-full py-2 px-4 mt-4 bg-green-500 text-white rounded-md hover:bg-green-600 focus:outline-none"
        >
          Submit
        </button>
      </form>
    </article>
  );
};

export default ArtForm;

// client/src/views/ArtForm.vue
<template>
  <div class="art-form">
    <h1>Dunedin School of Art - SITE 2022</h1>

    <span class="page-info"
      >You can find your entry information here -
      <a
        href="https://dunedin-school-of-art-site-22.herokuapp.com/entries"
        target="_blank"
        >https://dunedin-school-of-art-site-22.herokuapp.com/entries</a
      ></span
    >

    <hr />

        <span class="page-info"
      >Fill out the following form to add your art to the catalogue.</span
    >

    <p class="page-message" v-html="message"></p>
    <form autocomplete="off" class="art-form-form">
      <div class="details-wrapper">
        <label>Entry Information</label>
        <input
          v-model="formData.firstName"
          type="text"
          placeholder="First Name"
        />
        <input
          v-model="formData.lastName"
          type="text"
          placeholder="Last Name"
        />
      </div>
      <div class="ex-wrapper">
        <input
          v-model="formData.title"
          type="text"
          placeholder="Exhibition Title"
        />
        <input
          v-model="formData.siteMap"
          type="number"
          max="100"
          placeholder="SITE Map Number"
        />
        <label class="little-label"> SITE Map Number * </label>
      </div>
      <div class="section-wrapper">
        <select class="section-select" v-model="formData.section">
          <option v-for="section in sections" :key="section" :value="section">
            {{ section }}
          </option>
        </select>
        <label class="little-label"> Studio * </label>
      </div>
      <hr />
      <label> Add Catalogue Items </label>
      <div class="catalogue-items-wrapper">
        <ul class="catalogue-item-list">
          <li
            v-for="item in items"
            :key="item.id"
            @click.stop="selectedItem = item.id"
            :class="{ selected: item.id == selectedItem }"
          >
            Item {{ item.id }}
          </li>
        </ul>
        <CatalogueItem
          v-for="item in items"
          :key="item.id"
          :id="item.id"
          :hidden="selectedItem !== item.id"
          :mediums="mediums"
        >
        </CatalogueItem>
      </div>
      <input
        type="submit"
        @click.stop.prevent="addItem"
        class="add-item-btn"
        value="Create Another Item"
      />
      <hr />
      <span class="page-info">
        <strong
          >Please ensure the information above is correct before
          submitting.</strong
        >
      </span>
      <div class="submit-wrapper">
        <input type="submit" value="Submit" @click.stop.prevent="onSubmit" />
      </div>
    </form>
  </div>
</template>

<script>
import repo from '../repo';
import CatalogueItem from '../components/CatalogueItem';
export default {
  name: 'ArtForm',
  components: {
    CatalogueItem,
  },
  data() {
    return {
      message: null,
      sections: [],
      mediums: [],
      formData: {
        firstName: null,
        lastName: null,
        title: null,
        section: null,
        siteMap: 1,
      },
      selectedItem: 1,
    };
  },
  async created() {
    await this.load();
  },
  computed: {
    siteMapNumber() {
      return this.formData.siteMap;
    },
    items() {
      return this.$store.getters.items;
    },
  },
  watch: {
    siteMapNumber(newValue) {
      if (newValue > 100) {
        this.formData.siteMap = this.formData.siteMap.replace(/^./, '');
      }
      if (newValue < 1) {
        this.formData.siteMap = 1;
      }
    },
  },
  methods: {
    addItem() {
      this.$store.commit('add');
    },
    onError(error) {
      console.log({ error });
      if (error.response && error.response.data) {
        this.message = error.response.data;
        return;
      }

      this.message = 'Unknown error, server may be down.';
    },
    async load() {
      try {
        const res = await repo.getInfo();
        this.sections = res.data.sections;
        this.mediums = res.data.mediums;
        this.formData.section = this.sections[0];
      } catch (error) {
        this.onError(error);
      }
    },
    async onSubmit() {
      try {
        if (confirm('Press OK if your information is correct?')) {
          this.message = 'Submitting...';
          const items = this.$store.getters.items;
          const res = await repo.submitForm({
            ...this.formData,
            items: items,
          });
          window.location.reload();
          console.log('Thing was saved to the database.');
        } else {
          // Do nothing
        }
      } catch (error) {
        this.onError(error);
      }
    },
  },
};
</script>

<style lang="scss">
.art-form {
  margin-left: 9px;

  .page-info {
    font-size: 0.8em;
  }

  .page-message {
    font-size: 0.7em;
    margin: 0;
    text-align: center;
  }

  input,
  select {
    margin-left: 10px;
    margin-right: 10px;
  }

  .ex-wrapper {
    margin: 10px 0;
    input {
      &[type='number'] {
        width: 50px;
      }
    }
  }

  .catalogue-items-wrapper {
    display: flex;
    flex-grow: 1;
    flex-shrink: 0;
    flex-basis: 400px;

    .catalogue-item-list {
      min-height: 220px;
      max-height: 220px;
      overflow-y: auto;
      font-size: 0.8em;
      list-style: none;
      li {
        padding: 10px 20px;
        background: hsl(0, 0%, 96%);
        cursor: pointer;
        &.selected {
          background: hsl(204, 48%, 69%);
          color: #fff;
        }
        &:hover:not(.selected) {
          background: hsl(0, 0%, 75%);
        }
      }
    }

    .catalogue-item {
      margin: 0 20px;
    }
  }

  .submit-wrapper input {
    margin: 20px;
  }
}
</style>
