// dsoa-catalogue/src/components/CatalogueItem.jsx
const CatalogueItem = ({ id, item, onChange }) => (
  <div className="catalogue-item">
    <form className="catalogue-item-form" onChange={onChange}>
      <label className="little-label"> Title * </label>
      <div className="title-wrapper">
        <input
          type="text"
          required
          name="title"
          value={item.title}
          placeholder={`Item ${id}`}
          onChange={(e) => onChange(id, { ...item, title: e.target.value })}
        />
      </div>

      <label className="little-label"> Medium * </label>
      <div className="title-wrapper">
        <input
          type="text"
          required
          name="medium"
          value={item.medium}
          placeholder="Medium"
          onChange={(e) => onChange(id, { ...item, medium: e.target.value })}
        />
      </div>

      <label className="little-label"> Dimensions (Optional) </label>
      <div className="dimensions-wrapper">
        <input
          type="text"
          name="dimensions"
          value={item.dimensions}
          placeholder="Dimensions"
          onChange={(e) => onChange(id, { ...item, dimensions: e.target.value })}
        />
        <label className="little-label">
          (Width x Height x Length) Centimetres
        </label>
      </div>

      <input
        type="checkbox"
        name="hasEdition"
        checked={item.hasEdition}
        onChange={(e) => onChange(id, { ...item, hasEdition: e.target.checked })}
      />
      <label className="little-label"> Does your item have editions? (Optional)</label>
      {item.hasEdition && (
        <div className="edition-wrapper">
          <label className="little-label"> How many? </label>
          <input
            type="number"
            name="editions"
            value={item.editions}
            onChange={(e) => onChange(id, { ...item, editions: e.target.value })}
          />
        </div>
      )}

      <input
        type="checkbox"
        name="nfs"
        checked={item.nfs}
        onChange={(e) => onChange(id, { ...item, nfs: e.target.checked })}
      />
      <label className="little-label"> Is your item for sale? * </label>
      {item.nfs && (
        <div className="dollars-wrapper">
          <label className="little-label"> NZ Dollars (NZD) </label>
          <input
            type="number"
            name="value"
            value={item.value}
            onChange={(e) => onChange(id, { ...item, value: e.target.value })}
          />
        </div>
      )}

      <span className="page-info">
        <strong>
          Please note that Otago Polytechnic takes a 25% commission.
        </strong>
      </span>
    </form>
  </div>
);

export default CatalogueItem;

// client/src/components/CatalogueItem.vue
<template>
  <div class="catalogue-item">
    <transition name="fade">
      <form class="catalogue-item-form" @change="updateState">
        <label class="little-label"> Title * </label>
        <div class="title-wrapper">
          <input
            type="text"
            required
            v-model="item.title"
            :placeholder="itemPlaceholder"
            @input="1"
          />
        </div>
        <label class="little-label"> Medium * </label>
        <div class="title-wrapper">
          <input
            type="text"
            required
            v-model="item.medium"
            placeholder="Medium"
          />
        </div>
        <label class="little-label"> Dimensions (Optional) </label>
        <div class="dimensions-wrapper">
          <input
            v-model="item.dimensions"
            type="text"
            placeholder="Dimensions"
            value="20x20x20"
          />
          <label class="little-label">
            (Width x Height x Length) Centimetres
          </label>
        </div>
        <input v-model="item.hasEdition" type="checkbox" />
        <label class="little-label"
          >Does your item have editions? (Optional)</label
        >
        <div class="edition-wrapper">
          <label v-if="item.hasEdition" class="little-label">How many?</label>
          <input v-if="item.hasEdition" v-model="item.editions" type="number" />
        </div>
        <input v-model="item.nfs" type="checkbox" />
        <label class="little-label">Is your item for sale? * </label>
        <div class="dollars-wrapper">
          <label v-if="item.nfs" class="little-label">NZ Dollars (NZD) </label>
          <input v-if="item.nfs" v-model="item.value" type="number" />
        </div>
        <span class="page-info">
          <strong
            >Please note that Otago Polytechnic takes a 25% commission.</strong
          >
        </span>
      </form>
    </transition>
  </div>
</template>

<script>
export default {
  name: 'CatalogueItem',
  data() {
    return {
      item: {
        title: null,
        medium: null,
        value: 0,
        nfs: false,
        dimensions: '20x20x20',
        hasEdition: false,
        editions: 0,
      },
    };
  },
  props: {
    id: {
      type: Number,
      required: true,
    },
  },
  methods: {
    updateState() {
      this.$store.commit('update', {
        id: this.id,
        title: this.item.title,
        medium: this.item.medium,
        value: this.item.value,
        nfs: this.item.nfs,
        dimensions: this.item.dimensions,
        hasEdition: this.item.hasEdition,
        editions: this.item.editions,
      });
    },
  },
  computed: {
    itemPlaceholder() {
      return `Item ${this.id}`;
    },
  },
};
</script>

<style lang="scss">
.catalogue-item {
  padding: 5px;

  .save-wrapper {
    margin: 10px 0;
    input {
      margin: 0 5px;
    }
  }

  .desc {
    font-size: 0.8em;
    margin: 5px 10px;
  }

  .title-wrapper {
    margin: 5px 0;
  }

  .dollars-wrapper {
    display: flex;
    align-items: center;
  }
}

@media only screen and (max-width: 1000px) {
  .catalogue-item {
    width: 80%;
  }
}
</style>
