// client/src/components/CatalogueItem.vue
<template>
  <div class="catalogue-item">
    <transition name="fade">
      <form class="catalogue-item-form" @change="updateState">
        <label class="little-label"> Title * </label>
        <div class="title-wrapper">
          <input
            type="text"
            required
            v-model="item.title"
            :placeholder="itemPlaceholder"
            @input="1"
          />
        </div>
        <label class="little-label"> Medium * </label>
        <div class="title-wrapper">
          <input
            type="text"
            required
            v-model="item.medium"
            placeholder="Medium"
          />
        </div>
        <label class="little-label"> Dimensions (Optional) </label>
        <div class="dimensions-wrapper">
          <input
            v-model="item.dimensions"
            type="text"
            placeholder="Dimensions"
            value="20x20x20"
          />
          <label class="little-label">
            (Width x Height x Length) Centimetres
          </label>
        </div>
        <input v-model="item.hasEdition" type="checkbox" />
        <label class="little-label"
          >Does your item have editions? (Optional)</label
        >
        <div class="edition-wrapper">
          <label v-if="item.hasEdition" class="little-label">How many?</label>
          <input v-if="item.hasEdition" v-model="item.editions" type="number" />
        </div>
        <input v-model="item.nfs" type="checkbox" />
        <label class="little-label">Is your item for sale? * </label>
        <div class="dollars-wrapper">
          <label v-if="item.nfs" class="little-label">NZ Dollars (NZD) </label>
          <input v-if="item.nfs" v-model="item.value" type="number" />
        </div>
        <span class="page-info">
          <strong
            >Please note that Otago Polytechnic takes a 25% commission.</strong
          >
        </span>
      </form>
    </transition>
  </div>
</template>

<script>
export default {
  name: 'CatalogueItem',
  data() {
    return {
      item: {
        title: null,
        medium: null,
        value: 0,
        nfs: false,
        dimensions: '20x20x20',
        hasEdition: false,
        editions: 0,
      },
    };
  },
  props: {
    id: {
      type: Number,
      required: true,
    },
  },
  methods: {
    updateState() {
      this.$store.commit('update', {
        id: this.id,
        title: this.item.title,
        medium: this.item.medium,
        value: this.item.value,
        nfs: this.item.nfs,
        dimensions: this.item.dimensions,
        hasEdition: this.item.hasEdition,
        editions: this.item.editions,
      });
    },
  },
  computed: {
    itemPlaceholder() {
      return `Item ${this.id}`;
    },
  },
};
</script>

<style lang="scss">
.catalogue-item {
  padding: 5px;

  .save-wrapper {
    margin: 10px 0;
    input {
      margin: 0 5px;
    }
  }

  .desc {
    font-size: 0.8em;
    margin: 5px 10px;
  }

  .title-wrapper {
    margin: 5px 0;
  }

  .dollars-wrapper {
    display: flex;
    align-items: center;
  }
}

@media only screen and (max-width: 1000px) {
  .catalogue-item {
    width: 80%;
  }
}
</style>

// client/src/components/CatalogueItem.jsx
import { useState } from "react";

const CatalogueItem = ({ id, item, onChange, onDelete, submitted, errors }) => {
  const [isOpen, setIsOpen] = useState(true);

  const toggleOpen = () => setIsOpen(!isOpen);

  const handleChange = (field, value) => {
    onChange(id, { ...item, [field]: value });
  };

  return (
    <article className="mb-6 p-4 border rounded-lg shadow-md bg-white">
      <header className="flex justify-between items-center">
        <h2 className="text-xl font-semibold text-gray-700">Item {id + 1}</h2>
        <div className="space-x-2">
          <button
            type="button"
            onClick={toggleOpen}
            className="text-sm text-blue-600 hover:underline"
          >
            {isOpen ? "Collapse" : "Expand"}
          </button>
          <button
            type="button"
            onClick={() => onDelete(id)}
            className="text-sm text-red-600 hover:underline"
          >
            Delete
          </button>
        </div>
      </header>

      {isOpen && (
        <form className="mt-4">
          <fieldset className="mb-4">
            <legend className="text-lg font-medium text-gray-700">
              Basic Information
            </legend>

            <label className="block text-gray-700 mt-2">Title</label>
            <input
              type="text"
              name="title"
              value={item.title}
              placeholder={`Item ${id + 1}`}
              onChange={(e) => handleChange("title", e.target.value)}
              className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
            />
            {submitted && errors?.item?.title && (
              <p className="text-red-500">{errors?.item?.title}</p>
            )}

            <label className="block text-gray-700 mt-2">Medium</label>
            <input
              type="text"
              name="medium"
              value={item.medium}
              placeholder="Medium"
              onChange={(e) => handleChange("medium", e.target.value)}
              className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
            />
            {submitted && errors?.item?.medium && (
              <p className="text-red-500">{errors?.item?.medium}</p>
            )}

            <label className="block text-gray-700 mt-2">
              Dimensions (width x height x length in cm)
            </label>
            <input
              type="text"
              name="dimensions"
              value={item.dimensions}
              placeholder="Dimensions"
              onChange={(e) => handleChange("dimensions", e.target.value)}
              className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
            />
            {submitted && errors?.item?.dimensions && (
              <p className="text-red-500">{errors?.item?.dimensions}</p>
            )}
          </fieldset>

          <fieldset className="mb-4">
            <legend className="text-lg font-medium text-gray-700">
              Edition Information
            </legend>
            <div className="flex items-center mt-2">
              <input
                type="checkbox"
                name="hasEdition"
                checked={item.hasEdition}
                onChange={(e) => handleChange("hasEdition", e.target.checked)}
                className="mr-2"
              />
              <label className="text-gray-700">
                Does your item have editions?
              </label>
            </div>

            {item.hasEdition && (
              <>
                <label className="block text-gray-700 mt-2">How many?</label>
                <input
                  type="number"
                  name="editions"
                  value={item.editions}
                  onChange={(e) => handleChange("editions", e.target.value)}
                  className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
                />
                {submitted && errors?.item?.editions && (
                  <p className="text-red-500">{errors?.item?.editions}</p>
                )}
              </>
            )}
          </fieldset>

          <fieldset className="mb-4">
            <legend className="text-lg font-medium text-gray-700">
              Sale Information
            </legend>
            <div className="flex items-center mt-2">
              <input
                type="checkbox"
                name="nfs"
                checked={item.nfs}
                onChange={(e) => handleChange("nfs", e.target.checked)}
                className="mr-2"
              />
              <label className="text-gray-700">Is your item for sale?</label>
            </div>

            {item.nfs && (
              <>
                <label className="block text-gray-700 mt-2">
                  Value (NZ Dollars)
                </label>
                <input
                  type="number"
                  name="value"
                  value={item.value}
                  onChange={(e) => handleChange("value", e.target.value)}
                  className="w-full p-2 border border-gray-300 rounded-md focus:outline-none focus:border-blue-500"
                />
                {submitted && submitted && errors?.item?.value && (
                  <p className="text-red-500">
                    {submitted && errors?.item?.value}
                  </p>
                )}
              </>
            )}
          </fieldset>
        </form>
      )}
    </article>
  );
};

export default CatalogueItem;
