// client/src/views/Entries.vue
<template>
  <div class="entries">
    <h1 class="title">Entries</h1>
    <span v-html="message" class="message"></span>
    <input
      @click.stop.prevent="onChangeSortBySection"
      type="submit"
      class="sort-mode-button"
      :value="sortBySectionText"
    />
    <ul class="entries-list">
      <li class="entry-li" v-for="entry in entries" :key="entry.uid">
        <router-link
          :title="entry.title"
          class="entry"
          :to="'/entries/' + entry.uid"
        >
          <span class="entry-title"
            >{{ entry.firstName }} {{ entry.lastName }}:
            <span class="bold">{{
              cutoff(entry.title) || 'Untitled'
            }}</span></span
          >
          <span class="entry-info">
            {{ sortBySection ? entry.section : entry.siteMap }}
          </span>
        </router-link>
      </li>
    </ul>
  </div>
</template>

<script>
import repo from '../repo';
export default {
  name: 'Entries',
  data() {
    return {
      message: 'Loading entries...',
      entries: [],
      sortBySection: true,
    };
  },
  computed: {
    sortBySectionText() {
      return `Sort by ${!this.sortBySection ? 'section' : 'site MAP number'}`;
    },
  },
  async created() {
    await this.load();
  },
  methods: {
    onChangeSortBySection() {
      this.sortBySection = !this.sortBySection;
      if (this.sortBySection) {
        this.entries.sort((a, b) => {
          if (a.section < b.section) {
            return -1;
          }
          if (a.section > b.section) {
            return 1;
          }
          return 0;
        });
      } else {
        this.entries.sort((a, b) => {
          if (a.siteMap < b.siteMap) {
            return -1;
          }
          return 1;
        });
      }
    },
    cutoff(text) {
      if (text && text.length > 20) {
        return `${text.substring(0, 20)}...`;
      } else {
        return text;
      }
    },
    async load() {
      try {
        const res = await repo.getEntries();
        this.entries = res.data;
        if (!this.entries || this.entries.length < 1) {
          this.message = 'No entries yet.';
        } else {
          this.message = 'Choose an entry to view.';
        }
      } catch (error) {
        this.message = 'Failed to load entries, server may be down.';
      }
    },
  },
};
</script>

<style lang="scss">
.entries {
  text-align: center;

  .sort-mode-button {
    display: block;
    margin: 20px auto;
  }

  .entries-list {
    overflow: auto;
    list-style: none;
    padding: 5px;
    width: 60%;
    margin: 0 auto;
    text-align: left;

    .entry {
      display: flex;
      justify-content: space-between;
      padding: 15px;
      background: hsl(0, 0%, 98%);
      color: hsl(0, 0%, 17%);
      text-decoration: none;
      margin: 4px;
      cursor: pointer;
      transition: background 200ms;

      &:hover {
        background: hsl(204, 48%, 69%);
        color: #fff;
      }

      .entry-info {
        font-size: 1.1em;
        font-weight: bold;
        color: #000;
        text-align: center;
        padding: 5px;
      }

      .bold {
        font-weight: bold;
      }
    }
  }

  @media only screen and (max-width: 800px) {
    .entries-list {
      width: 100%;
    }
  }
}
</style>

// client/src/components/Entries.jsx
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";

const Entries = () => {
  const apiBaseURL = import.meta.env.VITE_API_BASE_URL;

  const [message, setMessage] = useState("Loading entries...");
  const [entries, setEntries] = useState([]);
  const [sortByLastName, setSortByLastName] = useState(true);

  useEffect(() => {
    const loadEntries = async () => {
      try {
        const res = await fetch(`${apiBaseURL}/catalogue-items/`, {
          method: "GET",
          headers: {
            "Content-Type": "application/json",
          },
        });
        const data = await res.json();
        const entriesData = data.data || [];
        setEntries(entriesData);
        setMessage(
          entriesData.length > 0
            ? "Select an entry to view details."
            : "No entries found."
        );
      } catch (error) {
        setMessage("Failed to load entries.");
      }
    };
    loadEntries();
  }, []);

  const toggleSortBy = () => {
    setSortByLastName((prevSortByLastName) => !prevSortByLastName);
    const sortedEntries = [...entries].sort((a, b) => {
      if (sortByLastName) {
        return a.items[0]?.lastName?.localeCompare(b.items[0]?.lastName);
      } else {
        return (a.items[0]?.siteMap || 0) - (b.items[0]?.siteMap || 0);
      }
    });
    setEntries(sortedEntries);
  };

  return (
    <article className="max-w-3xl mx-auto p-6 bg-white shadow-md rounded-md">
      <header>
        <h1 className="text-2xl font-bold text-gray-700 mb-4">Entries</h1>
      </header>

      <section>
        <p className="text-gray-700 mb-4">{message}</p>
      </section>

      {entries.length > 0 && (
        <input
          onClick={toggleSortBy}
          type="button"
          value={`Sort By ${sortByLastName ? "SITE Map Number" : "Last Name"}`}
          className="w-full py-2 px-4 mb-4 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none cursor-pointer"
        />
      )}

      <ul>
        {entries.map((entry) => (
          <Link
            key={entry.uuid}
            title={entry.items[0]?.title}
            to={`/entries/${entry.uuid}`}
          >
            <li className="mb-2 p-4 border border-gray-300 rounded-md transition-transform duration-200 transform hover:-translate-y-1 hover:shadow-lg">
              <p className="text-gray-700">
                {entry.items[0]?.firstName} {entry.items[0]?.lastName}
              </p>
              <p className="text-gray-700">
                <span className="font-bold">SITE map number:</span>{" "}
                {entry.items[0]?.siteMap}
              </p>
              <p className="text-gray-700">
                <span className="font-bold">Section:</span>{" "}
                {entry.items[0]?.section}
              </p>
              <p className="text-gray-700">
                <span className="font-bold">Number of items:</span>{" "}
                {entry.count}
              </p>
            </li>
          </Link>
        ))}
      </ul>
    </article>
  );
};

export default Entries;
